- job:
    name: ci-dockerfiles-deployment
    project-type: freestyle
    defaults: global
    properties:
        - authorization:
            authenticated:
                - job-read
                - job-extended-read
                - job-discover
        - build-discarder:
            days-to-keep: 90
            num-to-keep: 200
        - build-blocker:
            use-build-blocker: true
            blocking-jobs:
              - "ci-docker*"
            block-level: 'NODE'
    disabled: false
    node: build-amd64-private
    concurrent: false
    display-name: 'CI Dockerfiles build/publish deployment'
    parameters:
        - string:
            name: GERRIT_PROJECT
            default: 'ci/dockerfiles'
            description: |
              Git project to build (also set by Gerrit trigger)
        - string:
            name: GERRIT_BRANCH
            default: 'master'
            description: |
              Git branch to build (also set by Gerrit trigger)
        - string:
            name: GERRIT_REFSPEC
            default: ''
    scm:
        - git:
            url: https://review.trustedfirmware.org/${GERRIT_PROJECT}
            refspec: ${GERRIT_REFSPEC}
            branches:
                - ${GERRIT_BRANCH}
            skip-tag: true
            clean:
                before: true
            choosing-strategy: gerrit
            basedir: dockerfiles
    triggers:
        - gerrit:
            server-name: 'review.trustedfirmware.org'
            trigger-on:
                - change-merged-event
            projects:
                - project-compare-type: 'PLAIN'
                  project-pattern: 'ci/dockerfiles'
                  branches:
                    - branch-compare-type: 'PLAIN'
                      branch-pattern: 'master'
            silent-start: true
    execution-strategy:
        sequential: false
    wrappers:
        - timestamps
        - credentials-binding:
            - text:
                credential-id: DOCKER_AUTH
                variable: DOCKER_AUTH
    builders:
        - shell:
            !include-raw: ci-dockerfiles-deployment/build-version.sh
        - build-name-setter:
            name: 'version.txt'
            file: true
        - shell:
            !include-raw: ci-dockerfiles-deployment/builders.sh
        - shell:
            !include-raw: ci-dockerfiles-deployment/publish.sh
    publishers:
        - trigger:
            project: 'ci-dockerslaves-cleanup'
        - email:
            recipients: 'linaro-infrastructure-errors@lists.linaro.org paul.sokolovsky@linaro.org'
